### ISSUE TITLE
opensta report units

### ISSUE THREAD

**Issue by SweeperAA** [efabless/openlane#36]
The opensta.min_max.rpt file seems to show min and max slack data. What units are being used in this report?  For example, my opensta.min_max.rpt has:
` ... `
`  2.00   12.00   clock vclk (rise edge)`
`  0.00   12.00   clock network delay (ideal)`
`  0.00   12.00   clock reconvergence pessimism`
` 12.00 ^ _35045_/CLK (sky130_fd_sc_hd__dfxtp_4)`
` -0.09   11.91   library setup time`
`  11.91   data required time`

`  11.91   data required time`
`  -11.08   data arrival time`

`  0.83   slack (MET)`

I would have guessed that these are in ns, but my .tcl and .sdc files specify 10ns clock periods:
config.tcl
`set ::env(CLOCK_PERIOD) "10.0"`

sky130A_sky130_fd_sc_hd_config.tcl
`set ::env(CLOCK_PERIOD) "10.000"`

project.sdc
`set_units -time ns
create_clock [get_ports clk]  -name core_clock  -period 10`

**Comment by agorararmard** [comment]
@SweeperAA Yes, they are in ns. But, the base.sdc in rc2 has an issue that we discovered a while ago. The clock period is fixed there to 12ns. So, you can use this [base.sdc](https://github.com/efabless/openlane/blob/develop/scripts/base.sdc) instead.

Also, switch lib_min and lib_max under the pdk configuration `$PDK_ROOT/sky130A/libs.tech/openlane/sky130_fd_sc_hd/config.tcl` to. 
```
LIB_MAX to sky130_fd_sc_hd__ss_100C_1v60.lib
LIB_MIN to sky130_fd_sc_hd__ff_n40C_1v95.lib
```
In order to get accurate STA. These were also fixed in the `develop` branch and will be coming to master soon.
